// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Revit_Transform.Flat.Schema
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct ChildItemBuffer : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static ChildItemBuffer GetRootAsChildItemBuffer(ByteBuffer _bb) { return GetRootAsChildItemBuffer(_bb, new ChildItemBuffer()); }
        public static ChildItemBuffer GetRootAsChildItemBuffer(ByteBuffer _bb, ChildItemBuffer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public ChildItemBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Geometry { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGeometryBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetGeometryBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetGeometryArray() { return __p.__vector_as_array<byte>(4); }
        public string Material { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMaterialBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
        public ArraySegment<byte>? GetMaterialBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetMaterialArray() { return __p.__vector_as_array<byte>(6); }
        public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(8); }
        public string Uuid { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUuidBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
        public ArraySegment<byte>? GetUuidBytes() { return __p.__vector_as_arraysegment(10); }
#endif
        public byte[] GetUuidArray() { return __p.__vector_as_array<byte>(10); }

        public static Offset<Schema.ChildItemBuffer> CreateChildItemBuffer(FlatBufferBuilder builder,
            StringOffset geometryOffset = default(StringOffset),
            StringOffset materialOffset = default(StringOffset),
            StringOffset nameOffset = default(StringOffset),
            StringOffset uuidOffset = default(StringOffset))
        {
            builder.StartTable(4);
            ChildItemBuffer.AddUuid(builder, uuidOffset);
            ChildItemBuffer.AddName(builder, nameOffset);
            ChildItemBuffer.AddMaterial(builder, materialOffset);
            ChildItemBuffer.AddGeometry(builder, geometryOffset);
            return ChildItemBuffer.EndChildItemBuffer(builder);
        }

        public static void StartChildItemBuffer(FlatBufferBuilder builder) { builder.StartTable(4); }
        public static void AddGeometry(FlatBufferBuilder builder, StringOffset geometryOffset) { builder.AddOffset(0, geometryOffset.Value, 0); }
        public static void AddMaterial(FlatBufferBuilder builder, StringOffset materialOffset) { builder.AddOffset(1, materialOffset.Value, 0); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
        public static void AddUuid(FlatBufferBuilder builder, StringOffset uuidOffset) { builder.AddOffset(3, uuidOffset.Value, 0); }
        public static Offset<Schema.ChildItemBuffer> EndChildItemBuffer(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<Schema.ChildItemBuffer>(o);
        }
    }


    static public class ChildItemBufferVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Geometry*/, false)
              && verifier.VerifyString(tablePos, 6 /*Material*/, false)
              && verifier.VerifyString(tablePos, 8 /*Name*/, false)
              && verifier.VerifyString(tablePos, 10 /*Uuid*/, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
