// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Revit_Transform.Flat.Schema
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct RoomBuffer : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static RoomBuffer GetRootAsRoomBuffer(ByteBuffer _bb) { return GetRootAsRoomBuffer(_bb, new RoomBuffer()); }
        public static RoomBuffer GetRootAsRoomBuffer(ByteBuffer _bb, RoomBuffer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public RoomBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUuidBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetUuidBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetUuidArray() { return __p.__vector_as_array<byte>(4); }
        public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
        public string Data { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
        public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(8); }
#endif
        public byte[] GetDataArray() { return __p.__vector_as_array<byte>(8); }
        public Schema.GeometryBuffer? Geometry { get { int o = __p.__offset(10); return o != 0 ? (Schema.GeometryBuffer?)(new Schema.GeometryBuffer()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<Schema.RoomBuffer> CreateRoomBuffer(FlatBufferBuilder builder,
            StringOffset uuidOffset = default(StringOffset),
            StringOffset nameOffset = default(StringOffset),
            StringOffset dataOffset = default(StringOffset),
            Offset<Schema.GeometryBuffer> geometryOffset = default(Offset<Schema.GeometryBuffer>))
        {
            builder.StartTable(4);
            RoomBuffer.AddGeometry(builder, geometryOffset);
            RoomBuffer.AddData(builder, dataOffset);
            RoomBuffer.AddName(builder, nameOffset);
            RoomBuffer.AddUuid(builder, uuidOffset);
            return RoomBuffer.EndRoomBuffer(builder);
        }

        public static void StartRoomBuffer(FlatBufferBuilder builder) { builder.StartTable(4); }
        public static void AddUuid(FlatBufferBuilder builder, StringOffset uuidOffset) { builder.AddOffset(0, uuidOffset.Value, 0); }
        public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
        public static void AddData(FlatBufferBuilder builder, StringOffset dataOffset) { builder.AddOffset(2, dataOffset.Value, 0); }
        public static void AddGeometry(FlatBufferBuilder builder, Offset<Schema.GeometryBuffer> geometryOffset) { builder.AddOffset(3, geometryOffset.Value, 0); }
        public static Offset<Schema.RoomBuffer> EndRoomBuffer(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<Schema.RoomBuffer>(o);
        }
    }


    static public class RoomBufferVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Uuid*/, false)
              && verifier.VerifyString(tablePos, 6 /*Name*/, false)
              && verifier.VerifyString(tablePos, 8 /*Data*/, false)
              && verifier.VerifyTable(tablePos, 10 /*Geometry*/, Schema.GeometryBufferVerify.Verify, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
